// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArdNxS1dybeW3zw-iv9C32Th21RFA6TI0',
    appId: '1:755713046844:web:8335b493745408ccfec639',
    messagingSenderId: '755713046844',
    projectId: 'sample-4fa28',
    authDomain: 'sample-4fa28.firebaseapp.com',
    storageBucket: 'sample-4fa28.appspot.com',
    measurementId: 'G-YQ68647NHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJcMMVvUEaQoMr0ULM7bNmYczLiA_gRU',
    appId: '1:755713046844:android:92a3093d443ec9c9fec639',
    messagingSenderId: '755713046844',
    projectId: 'sample-4fa28',
    storageBucket: 'sample-4fa28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsiUhoLFUVVRCntpOCNC2yeUWtAriTKhU',
    appId: '1:755713046844:ios:143f278260a4aa5efec639',
    messagingSenderId: '755713046844',
    projectId: 'sample-4fa28',
    storageBucket: 'sample-4fa28.appspot.com',
    iosClientId: '755713046844-bea076v6q0l9d8bsat69lm0opvjqa5m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsiUhoLFUVVRCntpOCNC2yeUWtAriTKhU',
    appId: '1:755713046844:ios:143f278260a4aa5efec639',
    messagingSenderId: '755713046844',
    projectId: 'sample-4fa28',
    storageBucket: 'sample-4fa28.appspot.com',
    iosClientId: '755713046844-bea076v6q0l9d8bsat69lm0opvjqa5m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );
}
